def get_hole_data
  hole_data = {
    "pebble" => [{
                  :img_url=>"https://www.pebblebeach.com/content/uploads/01PBGL16v2-ed-1560x600.jpg",
                  :hole_num=> 1,
                  :par=> 4,
                  :yardage=> 377,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/02PBGL16-ed-1560x600.jpg",
                  :hole_num=> 2,
                  :par=> 5,
                  :yardage=> 511,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/03PBGL16-ed-1560x600.jpg",
                  :hole_num=> 3,
                  :par=> 4,
                  :yardage=> 390,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/04PBGL16-ed-1560x600.jpg",
                  :hole_num=> 4,
                  :par=> 4,
                  :yardage=> 326,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/05PBGL16-ed-1560x600.jpg",
                  :hole_num=> 5,
                  :par=> 3,
                  :yardage=> 192,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/06PBGL16-ed-1560x600.jpg",
                  :hole_num=> 6,
                  :par=> 5,
                  :yardage=> 506,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/07PBGL16-ed-1560x600.jpg",
                  :hole_num=> 7,
                  :par=> 3,
                  :yardage=> 106,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/08PBGL16-ed-1560x600.jpg",
                  :hole_num=> 8,
                  :par=> 4,
                  :yardage=> 427,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/09PBGL16-ed-1560x600.jpg",
                  :hole_num=> 9,
                  :par=> 4,
                  :yardage=> 481,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/10PBGL16-ed-1560x600.jpg",
                  :hole_num=> 10,
                  :par=> 4,
                  :yardage=> 446,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/11PBGL16-ed-1560x600.jpg",
                  :hole_num=> 11,
                  :par=> 4,
                  :yardage=> 373,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/12PBGL16-ed-1560x600.jpg",
                  :hole_num=> 12,
                  :par=> 3,
                  :yardage=> 201,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/13PBGL16-ed-1560x600.jpg",
                  :hole_num=> 13,
                  :par=> 4,
                  :yardage=> 403,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/14PBGL16-ed-1560x600.jpg",
                  :hole_num=> 14,
                  :par=> 5,
                  :yardage=> 152,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/15PBGL16-ed-1560x600.jpg",
                  :hole_num=> 15,
                  :par=> 4,
                  :yardage=> 396,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/16PBGL16-ed-1560x600.jpg",
                  :hole_num=> 16,
                  :par=> 4,
                  :yardage=> 401,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/17PBGL16-ed-1560x600.jpg",
                  :hole_num=> 17,
                  :par=> 3,
                  :yardage=> 177,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/18PBGL16-ed-1560x600.jpg",
                  :hole_num=> 18,
                  :par=> 5,
                  :yardage=> 543,
                },
                  ],
    "spyglass" => [{
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map110.jpg",
                  :hole_num=> 1,
                  :par=> 5,
                  :yardage=> 595,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map22.jpg",
                  :hole_num=> 2,
                  :par=> 4,
                  :yardage=> 349,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map32.jpg",
                  :hole_num=> 3,
                  :par=> 3,
                  :yardage=> 172,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map42.jpg",
                  :hole_num=> 4,
                  :par=> 4,
                  :yardage=> 370,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map52.jpg",
                  :hole_num=> 3,
                  :par=> 3,
                  :yardage=> 197,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map62.jpg",
                  :hole_num=> 6,
                  :par=> 4,
                  :yardage=> 446,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map72.jpg",
                  :hole_num=> 7,
                  :par=> 5,
                  :yardage=> 529,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map82.jpg",
                  :hole_num=> 8,
                  :par=> 4,
                  :yardage=> 399,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map92.jpg",
                  :hole_num=> 9,
                  :par=> 4,
                  :yardage=> 431,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map102.jpg",
                  :hole_num=> 10,
                  :par=> 4,
                  :yardage=> 407,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map112.jpg",
                  :hole_num=> 11,
                  :par=> 5,
                  :yardage=> 528,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map122.jpg",
                  :hole_num=> 12,
                  :par=> 3,
                  :yardage=> 178,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map132.jpg",
                  :hole_num=> 13,
                  :par=> 4,
                  :yardage=> 460,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map142.jpg",
                  :hole_num=> 14,
                  :par=> 5,
                  :yardage=> 560,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map152.jpg",
                  :hole_num=> 15,
                  :par=> 3,
                  :yardage=> 130,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map162.jpg",
                  :hole_num=> 16,
                  :par=> 4,
                  :yardage=> 476,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map172.jpg",
                  :hole_num=> 17,
                  :par=> 4,
                  :yardage=> 325,
                },
                {
                  :img_url=>"https://www.pebblebeach.com/content/uploads/spyglasshill-golf-map182.jpg",
                  :hole_num=> 18,
                  :par=> 4,
                  :yardage=> 408,
                },
                  ]
    }
  return hole_data
end
